/**
 * Offentlig bransjedata for marketing-sider.
 * Kobles til BRANSJE_MODULES for moduler, men inneholder
 * markedsføringsinnhold, USPer, lovkrav og SEO-data.
 */

import type { LucideIcon } from "lucide-react";
import {
  HardHat,
  Zap,
  Anchor,
  Ship,
  Fuel,
  Fish,
  Mountain,
  HeartPulse,
  GraduationCap,
  UtensilsCrossed,
  TreePine,
  Truck,
  Factory,
  ShoppingBag,
  Wheat,
  Monitor,
  Building2,
  AlertCircle,
  ShieldCheck,
  BookOpen,
  ClipboardCheck,
  Flame,
  ListChecks,
  Target,
  FileText,
  Beaker,
  FlaskConical,
  Scale,
} from "lucide-react";

// ── Modulbeskrivelser ────────────────────────────────────────────────────────

export interface ModuleDescription {
  path: string;
  name: string;
  shortName: string;
  description: string;
  icon: LucideIcon;
}

export const MODULE_DESCRIPTIONS: Record<string, ModuleDescription> = {
  "/dashboard/health-safety-policy": {
    path: "/dashboard/health-safety-policy",
    name: "Health and safety policy",
    shortName: "H&S policy",
    description: "Living written policy: statement of intent, organisation and arrangements (HSWA s.2(3))",
    icon: BookOpen,
  },
  "/dashboard/hms-handbok": {
    path: "/dashboard/health-safety-policy",
    name: "Health and safety policy",
    shortName: "H&S policy",
    description: "Living written policy: statement of intent, organisation and arrangements (HSWA s.2(3))",
    icon: BookOpen,
  },
  "/dashboard/incidents": {
    path: "/dashboard/incidents",
    name: "Avvik og hendelser",
    shortName: "Avvik",
    description: "Rapportering, årsaksanalyse (5 Whys) og oppfølging av avvik",
    icon: AlertCircle,
  },
  "/dashboard/risks": {
    path: "/dashboard/risks",
    name: "Risikovurdering",
    shortName: "Risiko",
    description: "5x5-matrise, bransjemaler og automatisk handlingsplaner",
    icon: Target,
  },
  "/dashboard/rutiner": {
    path: "/dashboard/rutiner",
    name: "Rutiner og prosedyrer",
    shortName: "Rutiner",
    description: "Versjonerte rutiner med lesebekreftelse og gjennomgangspåminnelser",
    icon: FileText,
  },
  "/dashboard/inspections": {
    path: "/dashboard/inspections",
    name: "Vernerunder",
    shortName: "Vernerunder",
    description: "Digitale sjekklister, bildeopptak og automatisk tiltaksoppfølging",
    icon: ShieldCheck,
  },
  "/dashboard/training": {
    path: "/dashboard/training",
    name: "Opplæring og kompetanse",
    shortName: "Opplæring",
    description: "Kompetansematrise, sertifikatstyring og utløpsvarsler",
    icon: GraduationCap,
  },
  "/dashboard/fire-drills": {
    path: "/dashboard/fire-drills",
    name: "Brannøvelser",
    shortName: "Brannøvelser",
    description: "Planlegging, gjennomføring og dokumentasjon av brannøvelser",
    icon: Flame,
  },
  "/dashboard/annual-hms-plan": {
    path: "/dashboard/annual-hms-plan",
    name: "Årlig HMS-plan",
    shortName: "HMS-plan",
    description: "Årshjul med aktiviteter, frister og ansvarlige",
    icon: ListChecks,
  },
  "/dashboard/sja": {
    path: "/dashboard/sja",
    name: "Sikker Jobb Analyse (SJA)",
    shortName: "SJA",
    description: "Risikovurdering før farlige arbeidsoperasjoner",
    icon: ClipboardCheck,
  },
  "/dashboard/chemicals": {
    path: "/dashboard/chemicals",
    name: "Stoffkartotek",
    shortName: "Stoffkartotek",
    description: "Oversikt over kjemikalier med sikkerhetsdatablad og eksponeringsvurdering",
    icon: Beaker,
  },
  "/dashboard/exposure-register": {
    path: "/dashboard/exposure-register",
    name: "Eksponeringsregister",
    shortName: "Eksponering",
    description: "Registrering av arbeidstakeres eksponering for helsefarlige stoffer",
    icon: FlaskConical,
  },
  "/dashboard/construction-compliance": {
    path: "/dashboard/construction-compliance",
    name: "Byggherreforskriften",
    shortName: "SHA/Bygg",
    description: "SHA-plan, koordinering og samsvarserklæringer for byggeplasser",
    icon: HardHat,
  },
  "/dashboard/samsvarserklaringer": {
    path: "/dashboard/samsvarserklaringer",
    name: "Samsvarserklæringer",
    shortName: "Samsvar",
    description: "Elektroniske samsvarserklæringer iht. NEK 400 og FEL",
    icon: Scale,
  },
  "/dashboard/ik-mat": {
    path: "/dashboard/ik-mat",
    name: "IK-mat og HACCP",
    shortName: "IK-mat",
    description: "Temperaturlogg, HACCP-planer, allergenoversikt og Mattilsynet-tilsyn",
    icon: UtensilsCrossed,
  },
  "/dashboard/bht-nattarbeid": {
    path: "/dashboard/bht-nattarbeid",
    name: "BHT og nattarbeid",
    shortName: "BHT/Natt",
    description: "Helseundersøkelser og oppfølging av nattarbeidere",
    icon: HeartPulse,
  },
  "/dashboard/transport": {
    path: "/dashboard/transport",
    name: "Transportmodul",
    shortName: "Transport",
    description: "Kjøretøykontroll, sjåføropplæring og transportdokumentasjon",
    icon: Truck,
  },
  "/dashboard/aktivitetssikkerhet": {
    path: "/dashboard/aktivitetssikkerhet",
    name: "Aktivitetssikkerhet",
    shortName: "Aktivitet",
    description: "Sikkerhetsvurdering av opplevelsesaktiviteter og guidede turer",
    icon: TreePine,
  },
  "/dashboard/beredskap-reiseliv": {
    path: "/dashboard/beredskap-reiseliv",
    name: "Beredskapsplan",
    shortName: "Beredskap",
    description: "Beredskapsplaner, varslingslister og øvelsesdokumentasjon",
    icon: ShieldCheck,
  },
};

// ── Bransjedata ──────────────────────────────────────────────────────────────

export interface BransjePublicData {
  key: string;
  slug: string;
  label: string;
  description: string;
  icon: LucideIcon;
  heroTitle: string;
  heroDescription: string;
  usps: string[];
  legalRefs: { law: string; description: string }[];
  scenarios: { title: string; description: string }[];
  extraModulePaths: string[];
}

export const BRANSJE_PUBLIC_DATA: BransjePublicData[] = [
  {
    key: "construction",
    slug: "bygg-og-anlegg",
    label: "Bygg og anlegg",
    description: "Byggeplasser, entreprenorer, handverkere og anleggsarbeid",
    icon: HardHat,
    heroTitle: "HMS-system bygd for byggeplassen",
    heroDescription: "HMS Nova gir deg full kontroll over sikkerhet pa byggeplassen. SJA for risikofylte oppgaver, SHA-plan iht. byggherreforskriften, stoffkartotek og eksponeringsregister -- alt tilgjengelig pa mobil.",
    usps: [
      "SJA for alle farlige arbeidsoperasjoner pa byggeplass",
      "SHA-plan og samsvar med byggherreforskriften",
      "Stoffkartotek med sikkerhetsdatablad for kjemikalier",
      "Eksponeringsregister for stov, sveiserøyk og kjemikalier",
      "Digitale vernerunder med bildeopptak fra stedet",
      "Mobiloptimalisert -- fungerer i felten uten PC",
      "Automatisk varsling av HMS-ansvarlig ved nye avvik",
      "Levende HMS-handbok integrert i hele HMS-arbeidet",
    ],
    legalRefs: [
      { law: "Byggherreforskriften", description: "Krav til SHA-plan, koordinering og risikovurdering pa byggeplasser" },
      { law: "AML kap. 4", description: "Krav til fullt forsvarlig arbeidsmiljo" },
      { law: "Forskrift om utforelse av arbeid kap. 3 og 4", description: "Krav til arbeid i høyden, graving og stillasarbeid" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "Rask SJA for betongarbeid", description: "Formann oppretter SJA pa mobilen for betongstoping. Identifiserer farer, setter tiltak og far digital godkjenning fra HMS-ansvarlig for arbeidet starter." },
      { title: "Vernerunde pa byggeplass", description: "Verneombudet gjennomforer vernerunde med digital sjekkliste. Tar bilder av avvik, og tiltak opprettes automatisk til ansvarlig bas." },
      { title: "Avvikshåndtering med rotarsak", description: "En nestenulykke rapporteres pa 2 minutter via mobil. HMS-ansvarlig varsles automatisk, utfører årsaksanalyse og oppdaterer HMS-handboken med nye tiltak." },
    ],
    extraModulePaths: ["/dashboard/sja", "/dashboard/chemicals", "/dashboard/exposure-register", "/dashboard/construction-compliance"],
  },
  {
    key: "elektro",
    slug: "elektro-og-energi",
    label: "Elektro og energi",
    description: "Elektrisk installasjon, energiselskap og nettselskap",
    icon: Zap,
    heroTitle: "HMS-system for elektrobransjen",
    heroDescription: "Sikker jobbanalyse for strømforende arbeid, samsvarserklaeringer iht. NEK 400, og stoffkartotek for kjemikalier brukt i elektrisk installasjon.",
    usps: [
      "SJA tilpasset elektrisk arbeid og høyspenning",
      "Samsvarserklaeringer iht. NEK 400 og FEL",
      "Stoffkartotek for isolasjonsmidler og kjemikalier",
      "Kompetansematrise for sertifiserte elektrikere",
      "Vernerunder tilpasset elektriske installasjoner",
      "Digital signering av HMS-dokumenter",
      "Automatisk påminnelse om sertifikatfornyelse",
      "Integrert HMS-håndbok med lovkrav for elektro",
    ],
    legalRefs: [
      { law: "Forskrift om elektriske lavspenningsanlegg (FEL)", description: "Krav til utforelse, dokumentasjon og kontroll" },
      { law: "NEK 400", description: "Norsk standard for elektriske lavspenningsinstallasjoner" },
      { law: "FSE", description: "Forskrift om sikkerhet ved arbeid i og drift av elektriske anlegg" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "SJA for høyspenningsarbeid", description: "Montør oppretter SJA for arbeid på høyspenningsanlegg. Systemet foreslår relevante farer og tiltak basert pa tidligere SJA-er." },
      { title: "Samsvarserklæring", description: "Etter ferdigstilt installasjon genereres samsvarserklæring digitalt med alle relevante referanser til NEK 400." },
      { title: "Kompetanseoversikt", description: "Daglig leder ser hvilke sertifikater som utloper snart og planlegger oppfriskningskurs i god tid." },
    ],
    extraModulePaths: ["/dashboard/sja", "/dashboard/chemicals", "/dashboard/samsvarserklaringer"],
  },
  {
    key: "offshore",
    slug: "offshore-og-petroleum",
    label: "Offshore og petroleum",
    description: "Offshore-installasjoner, rigg og vedlikehold",
    icon: Anchor,
    heroTitle: "HMS-system for offshore og petroleum",
    heroDescription: "Komplett HMS-verktøy for offshore-installasjoner. SJA, stoffkartotek, eksponeringsregister og beredskapsplaner som tilfredsstiller petroleumsregelverket.",
    usps: [
      "SJA tilpasset offshore-operasjoner",
      "Eksponeringsregister for oljestoff og kjemikalier",
      "Beredskapsplaner med varslingslister",
      "Stoffkartotek med alle sikkerhetsdatablad",
      "Digitale vernerunder for offshore-installasjoner",
      "Oppfolging av arbeidstimer og hviletid",
      "Kompetansematrise med sertifikatstyring",
      "Full sporbarhet for Petroleumstilsynet",
    ],
    legalRefs: [
      { law: "Rammeforskriften", description: "Overordnede HMS-krav for petroleumsvirksomhet" },
      { law: "Styringsforskriften", description: "Krav til styring og ledelse av HMS" },
      { law: "Aktivitetsforskriften", description: "Krav til utforelse av aktiviteter pa sokkelen" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "SJA for kranoperasjon", description: "Kranforer og sikkerhetskoordinator gjennomforer SJA for loft av tungt utstyr. Digital godkjenning for jobben starter." },
      { title: "Beredskapsovelse", description: "Beredskapsleder planlegger og dokumenterer mønstring og evakueringsovelse med full sporbarhet." },
      { title: "Eksponeringsregistrering", description: "Arbeidstaker logger eksponering for boreslamkjemikalier. Systemet varsler dersom grenseverdier naermer seg." },
    ],
    extraModulePaths: ["/dashboard/sja", "/dashboard/chemicals", "/dashboard/exposure-register", "/dashboard/beredskap-reiseliv"],
  },
  {
    key: "marine",
    slug: "maritim-og-sjofart",
    label: "Maritim og sjøfart",
    description: "Skip, verft, havnevirksomhet og maritim service",
    icon: Ship,
    heroTitle: "HMS-system for maritim og sjøfart",
    heroDescription: "SJA for arbeid ombord, stoffkartotek tilpasset maritim industri, og eksponeringsregister for kjemikalier og stoy i skipsmiljo.",
    usps: [
      "SJA tilpasset maritime operasjoner",
      "Stoffkartotek for malingssystemer og kjemikalier",
      "Eksponeringsregister for stoy, vibrasjoner og kjemikalier",
      "Vernerunder tilpasset skips- og verftsarbeid",
      "Kompetanseoversikt for maritime sertifikater",
      "Dokumentasjon for Sjøfartsdirektoratet",
      "Beredskapsplaner for nødsituasjoner ombord",
      "Integrert HMS-håndbok med ISM-kode",
    ],
    legalRefs: [
      { law: "Skipssikkerhetsloven", description: "Krav til sikkerhet og arbeidsmiljo om bord pa skip" },
      { law: "ISM-koden", description: "International Safety Management -- krav til sikkerhetsstyring" },
      { law: "AML kap. 4", description: "Krav til fullt forsvarlig arbeidsmiljo" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "SJA for varmt arbeid", description: "For sveisearbeid i maskinrom gjennomfores SJA med brannvaktordning og godkjenning av sikkerhetsoffiser." },
      { title: "Eksponering for stoy", description: "Maskinist registrerer daglig stoyeksponering. Systemet beregner akkumulert dose og varsler ved grenseverdier." },
      { title: "Verfts-vernerunde", description: "HMS-koordinator gjennomforer vernerunde pa verft med digitale sjekklister for stillas, brannvern og orden." },
    ],
    extraModulePaths: ["/dashboard/sja", "/dashboard/chemicals", "/dashboard/exposure-register"],
  },
  {
    key: "oil_gas",
    slug: "olje-og-gass",
    label: "Olje og gass",
    description: "Raffineri, petrokjemi og gassanlegg",
    icon: Fuel,
    heroTitle: "HMS-system for olje- og gassindustrien",
    heroDescription: "Komplett HMS-losning for raffinerier, petrokjemiske anlegg og gassbehandling. SJA, eksponeringsregister og stoffkartotek med full sporbarhet.",
    usps: [
      "SJA for prosessoperasjoner og vedlikehold",
      "Eksponeringsregister for hydrokarboner og kjemikalier",
      "Stoffkartotek med alle sikkerhetsdatablad",
      "Beredskapsplaner tilpasset prosessanlegg",
      "Management of Change (MOC) dokumentasjon",
      "Kompetansematrise for prosessoperatorer",
      "Digital vernerunde for prosessomrader",
      "Full sporbarhet for Petroleumstilsynet og DSB",
    ],
    legalRefs: [
      { law: "Storulykkeforskriften", description: "Forebygging av storulykker med farlige kjemikalier" },
      { law: "Forskrift om handtering av farlig stoff", description: "Krav til trygg oppbevaring og bruk" },
      { law: "AML kap. 4", description: "Krav til fullt forsvarlig arbeidsmiljo" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "SJA for tankrevisjon", description: "For arbeid i lukket rom opprettes SJA med gassmaling, ventilasjon og redningsplan. Digital godkjenning av driftsleder." },
      { title: "Kjemikaliehandtering", description: "Ny kjemikalie tas i bruk. Stoffkartotek oppdateres, risikovurdering gjennomfores og eksponeringsregisteret knyttes til berørte ansatte." },
      { title: "Beredskapsovelse", description: "Årlig storulykkeovelse dokumenteres med deltakerliste, evalueringspunkter og forbedringstiltak i HMS-handboken." },
    ],
    extraModulePaths: ["/dashboard/sja", "/dashboard/chemicals", "/dashboard/exposure-register"],
  },
  {
    key: "fiskeri",
    slug: "fiskeri-og-havbruk",
    label: "Fiskeri og havbruk",
    description: "Fiske, oppdrett, foredling og havbruk",
    icon: Fish,
    heroTitle: "HMS-system for fiskeri og havbruk",
    heroDescription: "SJA for arbeid pa merd og fartoy, stoffkartotek for behandlingskjemikalier, og dokumentasjon som tilfredsstiller Sjøfartsdirektoratet og Mattilsynet.",
    usps: [
      "SJA for dykkeroperasjoner og merdarbeid",
      "Stoffkartotek for avlusningskjemikalier",
      "Kompetanseoversikt for maritime sertifikater",
      "Vernerunder tilpasset oppdrettsanlegg",
      "Dokumentasjon for Sjøfartsdirektoratet",
      "Hendelsesrapportering pa mobil fra båt",
      "Automatiske påminnelser om sertifikatfornyelse",
      "HMS-håndbok tilpasset akvakulturnaringen",
    ],
    legalRefs: [
      { law: "Akvakulturloven", description: "Krav til drift av oppdrettsanlegg" },
      { law: "Skipssikkerhetsloven", description: "Sikkerhet pa fiskefartoy" },
      { law: "AML kap. 4", description: "Krav til fullt forsvarlig arbeidsmiljo" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "SJA for dykkeroperasjon", description: "For notskifte gjennomfores SJA med dykkerlag. Risikoer vurderes og tiltak dokumenteres digitalt." },
      { title: "Avlusningsbehandling", description: "Ved bruk av avlusningskjemikalier oppdateres stoffkartotek og eksponerte ansatte registreres automatisk." },
      { title: "Sjøfartsdokumentasjon", description: "Kompetanseoversikten viser hvilke sertifikater som utloper og genererer rapporter for myndigheter." },
    ],
    extraModulePaths: ["/dashboard/sja", "/dashboard/chemicals"],
  },
  {
    key: "bergverk",
    slug: "bergverk-og-gruvedrift",
    label: "Bergverk og gruvedrift",
    description: "Gruver, steinbrudd, pukkverk og mineralutvinning",
    icon: Mountain,
    heroTitle: "HMS-system for bergverk og gruvedrift",
    heroDescription: "SJA for sprengningsarbeid og underjordsarbeid, eksponeringsregister for stov og vibrasjoner, og stoffkartotek tilpasset bergverksindustrien.",
    usps: [
      "SJA for sprengning, boring og knusing",
      "Eksponeringsregister for kvartsstov og vibrasjoner",
      "Stoffkartotek for sprengstoff og kjemikalier",
      "Digitale vernerunder for dagbrudd og underjord",
      "Kompetansematrise for bergsprengere",
      "Dokumentasjon for Direktoratet for mineralforvaltning",
      "Hendelsesrapportering med GPS-posisjon",
      "Automatisk sporbarhet for tilsynsmyndigheter",
    ],
    legalRefs: [
      { law: "Forskrift om sikkerhet, helse og arbeidsmiljo pa mineralutvinning", description: "HMS-krav for dagbrudd og underjordsdrift" },
      { law: "Forskrift om handtering av eksplosjonsfarlig stoff", description: "Krav til sprengningsarbeid" },
      { law: "AML kap. 4", description: "Krav til fullt forsvarlig arbeidsmiljo" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "SJA for sprengning", description: "Bergsprenger oppretter SJA med sikkerhetssoner, varslingsprosedyre og evakueringsplan. Digital godkjenning fra bergverksansvarlig." },
      { title: "Stovmaling", description: "Daglige stovmalinger registreres mot grenseverdier. Ved overskridelse varsles HMS-ansvarlig automatisk." },
      { title: "Maskinvedlikehold", description: "Planlagt vedlikehold av borerigger og knusere dokumenteres med sjekklister og reservedelslogg." },
    ],
    extraModulePaths: ["/dashboard/sja", "/dashboard/chemicals", "/dashboard/exposure-register"],
  },
  {
    key: "healthcare",
    slug: "helse-og-omsorg",
    label: "Helse og omsorg",
    description: "Sykehus, legekontor, sykehjem, hjemmetjeneste og omsorg",
    icon: HeartPulse,
    heroTitle: "HMS-system for helse og omsorg",
    heroDescription: "Stoffkartotek for medisiner og rengjoringsmidler, eksponeringsregister for biologiske faktorer, og BHT-oppfolging for nattarbeidere i helsesektoren.",
    usps: [
      "Stoffkartotek for medikamenter og desinfeksjonsmidler",
      "Eksponeringsregister for biologiske og kjemiske faktorer",
      "BHT-oppfølging for nattarbeid og turnus",
      "Avvikshåndtering tilpasset pasientrelaterte hendelser",
      "Vernerunder for sykehjem og hjemmetjeneste",
      "Kompetanseoversikt for helsepersonell",
      "Psykososialt arbeidsmiljø-modul",
      "HMS-håndbok tilpasset helse- og omsorgsforskriften",
    ],
    legalRefs: [
      { law: "Helsepersonelloven", description: "Krav til forsvarlig yrkesutovelse" },
      { law: "Forskrift om systematisk HMS i helse- og omsorgstjenesten", description: "Internkontrollkrav for helsevirksomheter" },
      { law: "AML § 10-11", description: "Saerregler for nattarbeid og helseundersokelser" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "Stikkskadehåndtering", description: "Ansatt rapporterer stikkskade via mobil. Systemet oppretter avvik med riktig oppfolgingsprosedyre og varsler HMS-ansvarlig." },
      { title: "Nattarbeidoppfolging", description: "Ansatte i turnusordning far automatisk innkalling til helseundersokelse iht. AML § 10-11." },
      { title: "Eksponering for rengjoringsmidler", description: "Renholder registrerer daglig eksponering for sterke rengjoringsmidler. Systemet overvaker mot grenseverdier." },
    ],
    extraModulePaths: ["/dashboard/chemicals", "/dashboard/exposure-register", "/dashboard/bht-nattarbeid"],
  },
  {
    key: "education",
    slug: "utdanning",
    label: "Utdanning",
    description: "Barnehager, skoler, høyskoler og universiteter",
    icon: GraduationCap,
    heroTitle: "HMS-system for skoler og barnehager",
    heroDescription: "Enkel HMS-løsning for utdanningssektoren. Stoffkartotek for laboratorier og verksteder, avvikshåndtering og dokumentasjon som tilfredsstiller krav fra Utdanningsdirektoratet.",
    usps: [
      "Stoffkartotek for laboratorier og verksteder",
      "Enkel avvikshåndtering for ansatte og ledere",
      "Vernerunder tilpasset skole- og barnehagemiljo",
      "Brannøvelsesdokumentasjon med evaluering",
      "Risikovurdering av undervisningsaktiviteter",
      "Kompetanseoversikt for pedagogisk personale",
      "HMS-håndbok tilpasset utdanningssektoren",
      "Psykososialt arbeidsmiljo og trivsel",
    ],
    legalRefs: [
      { law: "Opplaeringslova § 9A", description: "Elevenes rett til et trygt og godt skolemiljo" },
      { law: "Barnehageloven § 7", description: "Krav til internkontroll i barnehager" },
      { law: "AML kap. 4", description: "Krav til fullt forsvarlig arbeidsmiljo for ansatte" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "Kjemilab-risikovurdering", description: "Laerer gjennomforer risikovurdering for kjemiforsok. Stoffkartotek viser riktig verneutstyr for hver kjemikalie." },
      { title: "Brannøvelse pa skolen", description: "Rektor planlegger og dokumenterer halvårlig brannøvelse med evakueringstid, observasjoner og forbedringspunkter." },
      { title: "Avvik i skolemiljo", description: "Ansatt rapporterer ødelagt lekeplass-utstyr. Tiltak opprettes automatisk til vaktmester med frist." },
    ],
    extraModulePaths: ["/dashboard/chemicals"],
  },
  {
    key: "hospitality",
    slug: "hotell-og-restaurant",
    label: "Hotell og restaurant",
    description: "Hoteller, restauranter, kafeer, catering og kantine",
    icon: UtensilsCrossed,
    heroTitle: "HMS-system for hotell og restaurant",
    heroDescription: "IK-mat med HACCP-planer, temperaturlogg og allergenoversikt. Stoffkartotek for rengjøring, og BHT-oppfølging for ansatte i nattarbeid og turnus.",
    usps: [
      "IK-mat med HACCP-fareanalyse og CCP-punkter",
      "Daglig temperaturlogg for kjoling og frysing",
      "Allergenoversikt med alle 14 EU-allergener",
      "Smilefjesordning-dokumentasjon for Mattilsynet",
      "Stoffkartotek for rengjoringskjemikalier",
      "BHT-oppfølging for nattarbeid i hotell/restaurant",
      "Vernerunder tilpasset kjokken og serveringsomrader",
      "HMS-håndbok tilpasset NHO Reiseliv-standarden",
    ],
    legalRefs: [
      { law: "IK-mat-forskriften § 4 og § 5", description: "Internkontroll for næringsmiddelvirksomhet" },
      { law: "Forordning (EF) 852/2004 art. 5", description: "HACCP-krav for næringsmiddelbedrifter" },
      { law: "EU-forordning 1169/2011", description: "Obligatorisk allergeninformasjon til forbrukere" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "Daglig temperaturlogg", description: "Kokk registrerer temperatur i kjølerom og frysere via mobil. Avvik flagges automatisk og tiltak opprettes." },
      { title: "Mattilsynet-besok", description: "Etter tilsynsbesok registreres smilefjeskarakter, funn og oppfølgingsfrister. Systemet minner om frister." },
      { title: "Ny meny -- allergenoversikt", description: "Ny rett legges inn med alle 14 allergener markert. Oversikten er tilgjengelig for servitorer på mobil." },
    ],
    extraModulePaths: ["/dashboard/chemicals", "/dashboard/ik-mat", "/dashboard/bht-nattarbeid"],
  },
  {
    key: "aktivitet",
    slug: "aktivitet-og-opplevelse",
    label: "Aktivitet og opplevelse",
    description: "Aktivitetsparker, guider, sport og friluftsliv",
    icon: TreePine,
    heroTitle: "HMS-system for aktivitet og opplevelse",
    heroDescription: "SJA for guidede turer og aktiviteter, aktivitetssikkerhetsvurdering og beredskapsplaner. Dokumentasjon for DSB og forsikringsselskaper.",
    usps: [
      "SJA tilpasset friluftsaktiviteter og opplevelser",
      "Aktivitetssikkerhetsvurdering iht. forskriften",
      "Beredskapsplaner for tur- og aktivitetsledere",
      "Kompetansematrise for guider og instruktorer",
      "Hendelsesrapportering fra felten via mobil",
      "Brannøvelser og evakueringsplaner",
      "Risikovurdering for nye aktiviteter",
      "HMS-håndbok tilpasset opplevelsesnaringen",
    ],
    legalRefs: [
      { law: "Forskrift om sikkerhet ved aktiviteter", description: "Krav til risikovurdering og sikkerhetstiltak for tilrettelagte aktiviteter" },
      { law: "Produktkontrolloven § 3", description: "Aktsomhetsplikt for tjenester og aktiviteter" },
      { law: "AML kap. 4", description: "Krav til fullt forsvarlig arbeidsmiljo" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "SJA for klatreaktivitet", description: "Instruktor oppretter SJA for klatring med risikovurdering av vaer, utstyr og deltakerferdigheter." },
      { title: "Beredskapsplan for tur", description: "Turguide har beredskapsplan tilgjengelig pa mobil med nodnumre, forstehjelpsprosedyrer og evakueringsruter." },
      { title: "Aktivitetssikkerhetsvurdering", description: "Ny zipline-aktivitet far full sikkerhetsvurdering for den kan tilbys gjester. Dokumentert for DSB." },
    ],
    extraModulePaths: ["/dashboard/sja", "/dashboard/aktivitetssikkerhet", "/dashboard/beredskap-reiseliv"],
  },
  {
    key: "transport",
    slug: "transport-og-logistikk",
    label: "Transport og logistikk",
    description: "Busser, båter, taxier, gods og reisearrangorer",
    icon: Truck,
    heroTitle: "HMS-system for transport og logistikk",
    heroDescription: "Transportmodul med kjøretøykontroll, sjåføropplæring og SJA for risikofylte transporter. Dokumentasjon som tilfredsstiller Statens vegvesen og Sjøfartsdirektoratet.",
    usps: [
      "Transportmodul med kjoretoy- og fartoyregister",
      "SJA for spesialtransporter og farlig gods",
      "Sjåføropplæring med sertifikatstyring",
      "Kjøre- og hviletidsdokumentasjon",
      "Hendelsesrapportering fra sjåfor pa mobil",
      "Vernerunder for verksted og terminal",
      "Risikovurdering for nye transportruter",
      "HMS-håndbok tilpasset transportforskriften",
    ],
    legalRefs: [
      { law: "Yrkestransportloven", description: "Krav til loyve og drift av transportvirksomhet" },
      { law: "Forskrift om kjore- og hviletid", description: "Krav til dokumentasjon av arbeidstid for sjaforer" },
      { law: "ADR-regelverket", description: "Krav til transport av farlig gods" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "Daglig kjoretøykontroll", description: "Sjåfor gjennomforer digital dagskontroll av lastebil med sjekkliste. Mangler rapporteres automatisk til verksted." },
      { title: "SJA for farlig gods", description: "Transport av farlig gods krever SJA med ADR-klassifisering, verneutstyr og nødprosedyrer dokumentert." },
      { title: "Sjåforoppfølging", description: "Kompetanseoversikten viser hvilke ADR-sertifikater som utloper og planlegger oppfriskningskurs." },
    ],
    extraModulePaths: ["/dashboard/transport", "/dashboard/sja"],
  },
  {
    key: "manufacturing",
    slug: "industri-og-produksjon",
    label: "Industri og produksjon",
    description: "Fabrikker, produksjonsanlegg og verksted",
    icon: Factory,
    heroTitle: "HMS-system for industri og produksjon",
    heroDescription: "SJA for vedlikehold og operasjoner, stoffkartotek for industrikjemikalier, og eksponeringsregister for stov, stoy og kjemisk pavirkning.",
    usps: [
      "SJA for vedlikehold, ombygging og driftsstans",
      "Stoffkartotek for alle industrikjemikalier",
      "Eksponeringsregister for stoy, stov og kjemikalier",
      "Maskinvernsjekklister og vedlikeholdsplaner",
      "Lock-Out/Tag-Out (LOTO) dokumentasjon",
      "Kompetansematrise for maskinoperatorer",
      "Digitale vernerunder for produksjonsomrader",
      "HMS-håndbok med ISO 45001-referanser",
    ],
    legalRefs: [
      { law: "Maskinforskriften", description: "Krav til maskinsikkerhet og CE-merking" },
      { law: "Forskrift om tiltaks- og grenseverdier", description: "Grenseverdier for kjemisk og fysisk eksponering" },
      { law: "AML kap. 4", description: "Krav til fullt forsvarlig arbeidsmiljo" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "SJA for vedlikeholdsstans", description: "Vedlikeholdsleder oppretter SJA for planlagt driftsstans. LOTO-prosedyre dokumenteres og godkjennes digitalt." },
      { title: "Stoyeksponering", description: "Ansatte i produksjonen registrerer daglig stoyeksponering. Akkumulert dose beregnes mot 85 dB(A) grenseverdi." },
      { title: "Ny kjemikalie", description: "Ved innforing av nytt rengjoringsmiddel oppdateres stoffkartotek, SDS lastes opp og berørte ansatte far opplaering." },
    ],
    extraModulePaths: ["/dashboard/sja", "/dashboard/chemicals", "/dashboard/exposure-register"],
  },
  {
    key: "retail",
    slug: "handel-og-service",
    label: "Handel og service",
    description: "Butikker, kjeder, service og kundebehandling",
    icon: ShoppingBag,
    heroTitle: "HMS-system for handel og service",
    heroDescription: "Enkel HMS-losning for butikker og servicebedrifter. Stoffkartotek for rengjoringsprodukter, ergonomiske vurderinger og psykososialt arbeidsmiljo.",
    usps: [
      "Stoffkartotek for rengjorings- og vedlikeholdsprodukter",
      "Enkel avvikshåndtering for butikkansatte",
      "Ergonomisk risikovurdering for kasse og lager",
      "Vernerunder tilpasset butikk- og lagermiljo",
      "Brannøvelser og evakueringsplaner",
      "Psykososialt arbeidsmiljo og trivsel",
      "Opplaeringsmodul for nyansatte",
      "HMS-håndbok tilpasset handelsnaringen",
    ],
    legalRefs: [
      { law: "AML § 4-1 til § 4-4", description: "Krav til fysisk og psykososialt arbeidsmiljo" },
      { law: "Forskrift om arbeid ved dataskjerm", description: "Ergonomiske krav for kassapersonale" },
      { law: "AML kap. 4", description: "Krav til fullt forsvarlig arbeidsmiljo" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "Ran eller trussel", description: "Etter en hendelse med truende kunde rapporterer ansatt avvik pa mobil. HMS-ansvarlig varsles og oppfolging igangsettes." },
      { title: "Ergonomivurdering", description: "Verneombudet gjennomforer ergonomisk vurdering av kassearbeidsplasser med digital sjekkliste." },
      { title: "Nyansatt-opplaering", description: "Ny butikkmedarbeider far automatisk tildelt HMS-opplaering med frist og kvittering." },
    ],
    extraModulePaths: ["/dashboard/chemicals"],
  },
  {
    key: "agriculture",
    slug: "landbruk",
    label: "Landbruk",
    description: "Gårdsdrift, skogbruk, dyrehold og planteproduksjon",
    icon: Wheat,
    heroTitle: "HMS-system for landbruk og skogbruk",
    heroDescription: "SJA for skogsdrift og maskinarbeid, stoffkartotek for plantevernmidler og gjodsel, og enkel HMS-dokumentasjon for gardbrukere.",
    usps: [
      "SJA for hogst, sprøyting og maskinarbeid",
      "Stoffkartotek for plantevernmidler og gjodsel",
      "Kompetansematrise for sprøytesertifikat og motorsag",
      "Vernerunder tilpasset gård og skogsdrift",
      "Hendelsesrapportering fra felten via mobil",
      "Brannøvelser for driftsbygninger",
      "Risikovurdering for sesongarbeid",
      "Enkel HMS-håndbok for sma bruk",
    ],
    legalRefs: [
      { law: "Forskrift om plantevernmidler", description: "Krav til bruk, lagring og dokumentasjon av plantevernmidler" },
      { law: "Forskrift om organisering, ledelse og medvirkning kap. 15", description: "Saerregler for alenearbeid i landbruket" },
      { law: "AML kap. 4", description: "Krav til fullt forsvarlig arbeidsmiljo" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "SJA for hogst", description: "For trehogging oppretter bonden SJA med sikkerhetssoner, verneutstyr og oppgavefordeling mellom skogsarbeidere." },
      { title: "Plantevernsprøyting", description: "Ved sprøyting registreres preparat, mengde og vaerforhold. Systemet sjekker at sprøytesertifikat er gyldig." },
      { title: "Sesongarbeidere", description: "Innleid arbeidskraft far automatisk HMS-opplaering og kvitterer for leste rutiner for de starter arbeidet." },
    ],
    extraModulePaths: ["/dashboard/sja", "/dashboard/chemicals"],
  },
  {
    key: "technology",
    slug: "teknologi-og-it",
    label: "Teknologi og IT",
    description: "Programvare, IT-drift, konsulentvirksomhet og kontor",
    icon: Monitor,
    heroTitle: "HMS-system for teknologi og kontor",
    heroDescription: "Enkel og oversiktlig HMS for kontorbedrifter. Fokus pa ergonomi, psykososialt arbeidsmiljo, brannvern og systematisk HMS-arbeid uten unødvendig kompleksitet.",
    usps: [
      "Ergonomisk risikovurdering for kontorarbeidsplasser",
      "Psykososialt arbeidsmiljo og medarbeiderundersokelser",
      "Brannøvelser og evakueringsplaner",
      "Enkel avvikshåndtering for kontormiljo",
      "Opplaeringsmodul for nyansatte",
      "Arlig HMS-plan med automatiske påminnelser",
      "Vernerunder tilpasset kontormiljo",
      "HMS-håndbok som dekker IK-HMS § 5 fullstendig",
    ],
    legalRefs: [
      { law: "Forskrift om arbeid ved dataskjerm", description: "Krav til ergonomi, belysning og pauser ved skjermarbeid" },
      { law: "AML § 4-3", description: "Krav til psykososialt arbeidsmiljo" },
      { law: "AML kap. 4", description: "Krav til fullt forsvarlig arbeidsmiljo" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
    ],
    scenarios: [
      { title: "Ergonomirunde", description: "Verneombudet gjennomforer ergonomisk sjekk av kontorplasser med digital sjekkliste. Tiltak opprettes for justeringer." },
      { title: "Psykososialt arbeidsmiljo", description: "Arlig undersokelse av arbeidsmiljo gjennomfores. Resultater kobles til HMS-handbok og handlingsplan." },
      { title: "Onboarding", description: "Ny ansatt far automatisk tildelt HMS-opplaering, brannrutiner og signerer HMS-handboken digitalt." },
    ],
    extraModulePaths: [],
  },
  {
    key: "other",
    slug: "annen-bransje",
    label: "Annen bransje",
    description: "Øvrige virksomheter",
    icon: Building2,
    heroTitle: "HMS-system for alle bransjer",
    heroDescription: "HMS Nova tilpasses enkelt til din bransje. Kjernefunksjonene dekker alle lovkrav i internkontrollforskriften, og du kan legge til bransjespesifikke moduler etter behov.",
    usps: [
      "Tilpasses din bransje med moduler etter behov",
      "Stoffkartotek for kjemikalier og farlige stoffer",
      "Komplett avvikshåndtering med årsaksanalyse",
      "Risikovurdering med 5x5-matrise",
      "Digitale vernerunder med sjekklister",
      "Kompetanseoversikt og opplaeringsplan",
      "HMS-håndbok som dekker IK-HMS § 5",
      "Fra 300 kr/mnd -- alt inkludert",
    ],
    legalRefs: [
      { law: "Arbeidsmiljoloven", description: "Krav til forsvarlig arbeidsmiljo for alle virksomheter" },
      { law: "IK-HMS § 5", description: "Systematisk HMS-arbeid og internkontroll" },
      { law: "AML § 3-1", description: "Arbeidsgivers plikt til systematisk HMS-arbeid" },
    ],
    scenarios: [
      { title: "Kom i gang pa 15 minutter", description: "Velg bransje under onboarding og far ferdig oppsatt HMS-system med relevante moduler og maler." },
      { title: "Tilpass etter behov", description: "Start med basisfunksjoner og legg til SJA, stoffkartotek eller andre moduler nar behovet oppstår." },
      { title: "Dokumentasjon for tilsyn", description: "Når Arbeidstilsynet kommer pa besøk har du all dokumentasjon klar -- digitalt og sporbart." },
    ],
    extraModulePaths: ["/dashboard/chemicals"],
  },
];

export function getBransjeBySlug(slug: string): BransjePublicData | undefined {
  return BRANSJE_PUBLIC_DATA.find((b) => b.slug === slug);
}

export function getAllBransjeSlugs(): string[] {
  return BRANSJE_PUBLIC_DATA.map((b) => b.slug);
}
