import {
  AlertTriangle,
  FileText,
  ShieldAlert,
  ClipboardCheck,
  GraduationCap,
  CheckSquare,
  Beaker,
  Flame,
  Droplets,
  Zap,
  Building2,
  UtensilsCrossed,
  Stethoscope,
  SprayCan,
  CalendarDays,
  BookOpen,
  HardHat,
  FileWarning,
  Heart,
  Leaf,
  ShieldCheck,
  Search,
  Users,
  MessageSquareWarning,
  MessageSquare,
  ScrollText,
  type LucideIcon,
  BarChart3,
  ListTodo,
  Sparkles,
  Activity,
  Clock,
  Siren,
  Gauge,
  Megaphone,
  Scale,
  Truck,
  TreePine,
  PersonStanding,
  MapPin,
  Moon,
  UserCheck,
  Radar,
  BookOpenCheck,
} from "lucide-react";
import { menuPathsToWidgetIds } from "@/lib/menu-widget-sync";
import { CORE_HSEQ_NAV_HREFS } from "@/lib/dashboard-nav-config";

export interface WidgetDefinition {
  id: string;
  label: string;
  description: string;
  icon: LucideIcon;
  href: string;
  category: WidgetCategory;
  color: string;
  bgColor: string;
  borderColor: string;
  permission?: string;
  isAdvanced?: boolean;
}

export type WidgetCategory =
  | "hms"
  | "sikkerhet"
  | "helse"
  | "dokumenter"
  | "personal"
  | "kvalitet"
  | "spesial";

export const WIDGET_CATEGORIES: Record<WidgetCategory, { label: string; color: string }> = {
  hms: { label: "HSEQ core", color: "text-blue-700" },
  sikkerhet: { label: "Safety & emergency", color: "text-red-700" },
  helse: { label: "Health & environment", color: "text-emerald-700" },
  dokumenter: { label: "Documents & procedures", color: "text-slate-700" },
  personal: { label: "People & organisation", color: "text-amber-700" },
  kvalitet: { label: "Quality & improvement", color: "text-indigo-700" },
  spesial: { label: "Dashboard widgets", color: "text-purple-700" },
};

export const WIDGET_REGISTRY: WidgetDefinition[] = [
  // HMS Kjerne
  {
    id: "incidents",
    label: "Accident book",
    description: "Injuries, near misses and RIDDOR-reportable events",
    icon: AlertTriangle,
    href: "/dashboard/incidents",
    category: "hms",
    color: "text-orange-700",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    permission: "incidents",
  },
  {
    id: "risks",
    label: "Risk assessments",
    description: "Suitable and sufficient risk assessments (MHSWR 1999)",
    icon: ShieldAlert,
    href: "/dashboard/risks",
    category: "hms",
    color: "text-red-700",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    permission: "risks",
    isAdvanced: true,
  },
  {
    id: "actions",
    label: "Actions",
    description: "Corrective and preventive actions",
    icon: CheckSquare,
    href: "/dashboard/actions",
    category: "hms",
    color: "text-blue-700",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    permission: "actions",
  },
  {
    id: "inspections",
    label: "Inspections",
    description: "Workplace inspections and safety tours",
    icon: ClipboardCheck,
    href: "/dashboard/inspections",
    category: "hms",
    color: "text-teal-700",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    permission: "inspections",
  },
  {
    id: "sja",
    label: "RAMS",
    description: "Risk assessment and method statement",
    icon: HardHat,
    href: "/dashboard/sja",
    category: "hms",
    color: "text-yellow-700",
    bgColor: "bg-yellow-50",
    borderColor: "border-yellow-200",
    permission: "sja",
  },
  {
    id: "ruh",
    label: "Incident reports",
    description: "Accident and dangerous occurrence reports",
    icon: FileWarning,
    href: "/dashboard/ruh",
    category: "hms",
    color: "text-amber-700",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
    permission: "ruh",
  },
  {
    id: "training",
    label: "Training",
    description: "Training and competence records (HSWA s.2)",
    icon: GraduationCap,
    href: "/dashboard/training",
    category: "hms",
    color: "text-purple-700",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
    permission: "training",
  },

  // Sikkerhet & Beredskap
  {
    id: "fire-safety",
    label: "Fire drills",
    description: "Plan, run and record fire drills (Fire Safety Order 2005)",
    icon: Flame,
    href: "/dashboard/fire-drills",
    category: "sikkerhet",
    color: "text-red-600",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    permission: "inspections",
  },
  {
    id: "electrical",
    label: "Compliance certificates",
    description: "Electrical, plumbing, ventilation and other trades",
    icon: Zap,
    href: "/dashboard/samsvarserklaringer",
    category: "sikkerhet",
    color: "text-yellow-600",
    bgColor: "bg-yellow-50",
    borderColor: "border-yellow-200",
  },
  {
    id: "water-safety",
    label: "Water",
    description: "Water safety and legionella control",
    icon: Droplets,
    href: "/dashboard/procedures?q=vann",
    category: "sikkerhet",
    color: "text-cyan-600",
    bgColor: "bg-cyan-50",
    borderColor: "border-cyan-200",
  },
  {
    id: "elevator",
    label: "Lifts",
    description: "Lift inspection and maintenance",
    icon: Building2,
    href: "/dashboard/procedures?q=heis",
    category: "sikkerhet",
    color: "text-slate-600",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
  },
  {
    id: "bcm",
    label: "Emergency planning",
    description: "Emergency plans and business continuity",
    icon: ShieldCheck,
    href: "/dashboard/bcm",
    category: "sikkerhet",
    color: "text-rose-700",
    bgColor: "bg-rose-50",
    borderColor: "border-rose-200",
    permission: "bcm",
    isAdvanced: true,
  },

  // Helse & Miljø
  {
    id: "chemicals",
    label: "COSHH",
    description: "Hazardous substances assessments and SDS (COSHH 2002)",
    icon: Beaker,
    href: "/dashboard/chemicals",
    category: "helse",
    color: "text-emerald-700",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    permission: "chemicals",
  },
  {
    id: "medicine",
    label: "Medicines",
    description: "Medicine handling and records",
    icon: Stethoscope,
    href: "/dashboard/procedures?q=medisin",
    category: "helse",
    color: "text-pink-600",
    bgColor: "bg-pink-50",
    borderColor: "border-pink-200",
  },
  {
    id: "medical-equipment",
    label: "Medical devices",
    description: "Medical equipment register and maintenance",
    icon: Siren,
    href: "/dashboard/procedures?q=medisinsk%20utstyr",
    category: "helse",
    color: "text-rose-600",
    bgColor: "bg-rose-50",
    borderColor: "border-rose-200",
  },
  {
    id: "cleaning",
    label: "Cleaning",
    description: "Cleaning checks and hygiene",
    icon: SprayCan,
    href: "/dashboard/procedures?q=renhold",
    category: "helse",
    color: "text-sky-600",
    bgColor: "bg-sky-50",
    borderColor: "border-sky-200",
  },
  {
    id: "food-safety",
    label: "Food safety",
    description: "Food safety and hygiene controls",
    icon: UtensilsCrossed,
    href: "/dashboard/procedures?q=mat",
    category: "helse",
    color: "text-green-600",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
  },
  {
    id: "wellbeing",
    label: "Wellbeing",
    description: "Psychosocial working environment and wellbeing",
    icon: Heart,
    href: "/dashboard/wellbeing",
    category: "helse",
    color: "text-pink-700",
    bgColor: "bg-pink-50",
    borderColor: "border-pink-200",
    permission: "wellbeing",
  },
  {
    id: "environment",
    label: "Environment",
    description: "Environmental management (ISO 14001)",
    icon: Leaf,
    href: "/dashboard/environment",
    category: "helse",
    color: "text-green-700",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    permission: "environment",
    isAdvanced: true,
  },

  // Dokumenter & Rutiner
  {
    id: "documents",
    label: "Documents",
    description: "Controlled documents and version history",
    icon: FileText,
    href: "/dashboard/documents",
    category: "dokumenter",
    color: "text-slate-700",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
    permission: "documents",
  },
  {
    id: "routines",
    label: "Procedures",
    description: "Company procedures, instructions and arrangements",
    icon: BookOpen,
    href: "/dashboard/procedures",
    category: "dokumenter",
    color: "text-indigo-600",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
  },

  // Personal & Administrasjon
  {
    id: "absence",
    label: "Leave / absence",
    description: "Absence, annual leave and time off",
    icon: CalendarDays,
    href: "/dashboard/time-registration",
    category: "personal",
    color: "text-amber-600",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
  },
  {
    id: "organization",
    label: "Organisation",
    description: "Organisation chart (HSWA s.2 — organisation)",
    icon: Users,
    href: "/dashboard/organisasjonskart",
    category: "personal",
    color: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
  },
  {
    id: "meetings",
    label: "Meetings",
    description: "Safety committee and safety representative meetings",
    icon: CalendarDays,
    href: "/dashboard/meetings",
    category: "personal",
    color: "text-indigo-600",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
    permission: "meetings",
    isAdvanced: true,
  },

  // Kvalitet & Forbedring
  {
    id: "audits",
    label: "Audits",
    description: "Internal and external audits",
    icon: Search,
    href: "/dashboard/audits",
    category: "kvalitet",
    color: "text-indigo-700",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
    permission: "audits",
    isAdvanced: true,
  },
  {
    id: "complaints",
    label: "Complaints",
    description: "Customer complaints and quality issues",
    icon: MessageSquareWarning,
    href: "/dashboard/complaints",
    category: "kvalitet",
    color: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    permission: "complaints",
    isAdvanced: true,
  },
  {
    id: "feedback",
    label: "Feedback",
    description: "Customer feedback and improvement ideas",
    icon: MessageSquare,
    href: "/dashboard/feedback",
    category: "kvalitet",
    color: "text-sky-600",
    bgColor: "bg-sky-50",
    borderColor: "border-sky-200",
    permission: "feedback",
    isAdvanced: true,
  },
  {
    id: "risk-register",
    label: "Risk register",
    description: "Company-wide risk register",
    icon: ScrollText,
    href: "/dashboard/risk-register",
    category: "kvalitet",
    color: "text-red-600",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    permission: "riskRegister",
    isAdvanced: true,
  },

  // Ledelse & Oversikt
  {
    id: "hms-cockpit",
    label: "HSEQ overview",
    description: "HSEQ score, trends and improvement actions",
    icon: Gauge,
    href: "/dashboard/hms-cockpit",
    category: "kvalitet",
    color: "text-violet-700",
    bgColor: "bg-violet-50",
    borderColor: "border-violet-200",
    permission: "hmsCockpit",
  },
  {
    id: "hms-handbok",
    label: "Health and safety policy",
    description: "Living health and safety policy (HSWA s.2)",
    icon: BookOpenCheck,
    href: "/dashboard/health-safety-policy",
    category: "dokumenter",
    color: "text-blue-700",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    permission: "hmsHandbok",
  },
  {
    id: "annual-hms-plan",
    label: "Annual H&S plan",
    description: "Annual plan for health and safety work",
    icon: CalendarDays,
    href: "/dashboard/annual-hms-plan",
    category: "kvalitet",
    color: "text-teal-700",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    permission: "annualHmsPlan",
  },
  {
    id: "management-reviews",
    label: "Management review",
    description: "Management review of the HSEQ system (ISO 45001)",
    icon: Users,
    href: "/dashboard/management-reviews",
    category: "kvalitet",
    color: "text-slate-700",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
    permission: "managementReviews",
    isAdvanced: true,
  },
  {
    id: "legal-register",
    label: "Legal register",
    description: "Laws and regulations that apply to the company",
    icon: Scale,
    href: "/dashboard/juridisk-register",
    category: "dokumenter",
    color: "text-amber-700",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
    permission: "legalRegister",
  },
  {
    id: "whistleblowing",
    label: "Whistleblowing",
    description: "Confidential reporting channel (PIDA 1998)",
    icon: Megaphone,
    href: "/dashboard/whistleblowing",
    category: "kvalitet",
    color: "text-red-700",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    permission: "whistleblowing",
    isAdvanced: true,
  },
  {
    id: "employee-reviews",
    label: "Appraisals",
    description: "Plan and record employee appraisals",
    icon: UserCheck,
    href: "/dashboard/medarbeidersamtale",
    category: "personal",
    color: "text-violet-600",
    bgColor: "bg-violet-50",
    borderColor: "border-violet-200",
    permission: "employeeReviews",
    isAdvanced: true,
  },

  // Bransje-spesifikke moduler
  {
    id: "exposure-register",
    label: "Exposure register",
    description: "Health surveillance records for hazardous substances (COSHH 40 years)",
    icon: Radar,
    href: "/dashboard/exposure-register",
    category: "helse",
    color: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    permission: "exposureRegister",
  },
  {
    id: "construction-compliance",
    label: "CDM",
    description: "Construction Design and Management 2015 — duty holders, CPP, F10",
    icon: HardHat,
    href: "/dashboard/construction-compliance",
    category: "sikkerhet",
    color: "text-amber-700",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
    permission: "constructionCompliance",
  },
  {
    id: "ik-mat",
    label: "Food safety / HACCP",
    description: "Food safety management and HACCP",
    icon: UtensilsCrossed,
    href: "/dashboard/ik-mat",
    category: "helse",
    color: "text-green-700",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    permission: "ikMat",
  },
  {
    id: "aktivitetssikkerhet",
    label: "Activity safety",
    description: "Safety for activities and visitor experiences",
    icon: PersonStanding,
    href: "/dashboard/aktivitetssikkerhet",
    category: "sikkerhet",
    color: "text-emerald-700",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    permission: "aktivitetssikkerhet",
  },
  {
    id: "transport",
    label: "Transport",
    description: "Operator licences, driver and vehicle checks",
    icon: Truck,
    href: "/dashboard/transport",
    category: "sikkerhet",
    color: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    permission: "transport",
  },
  {
    id: "bht-nattarbeid",
    label: "Occupational health / night work",
    description: "Occupational health and night-work arrangements",
    icon: Moon,
    href: "/dashboard/bht-nattarbeid",
    category: "helse",
    color: "text-indigo-700",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
    permission: "bhtNattarbeid",
  },
  {
    id: "beredskap-reiseliv",
    label: "Tourism emergency plan",
    description: "Emergency plan for tourism and hospitality sites",
    icon: MapPin,
    href: "/dashboard/beredskap-reiseliv",
    category: "sikkerhet",
    color: "text-teal-600",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    permission: "inspections",
  },
  {
    id: "projects",
    label: "Projects",
    description: "Project control and site-linked incidents",
    icon: TreePine,
    href: "/dashboard/projects",
    category: "kvalitet",
    color: "text-cyan-700",
    bgColor: "bg-cyan-50",
    borderColor: "border-cyan-200",
    permission: "incidents",
  },

  // Spesial-widgeter (dashboard-spesifikke)
  {
    id: "widget-task-center",
    label: "Task centre",
    description: "Actions that need follow-up",
    icon: ListTodo,
    href: "/dashboard/actions",
    category: "spesial",
    color: "text-blue-700",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
  },
  {
    id: "widget-hms-score",
    label: "HSEQ pulse",
    description: "Overall HSEQ status for inspection and audit",
    icon: BarChart3,
    href: "/dashboard/hms-pulse",
    category: "spesial",
    color: "text-emerald-700",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
  },
  {
    id: "widget-ai-assistant",
    label: "AI assistant",
    description: "Alerts and recommendations",
    icon: Sparkles,
    href: "/dashboard/notifications",
    category: "spesial",
    color: "text-purple-700",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
  },
  {
    id: "widget-activity-feed",
    label: "Activity",
    description: "Latest activity as alerts",
    icon: Activity,
    href: "/dashboard/notifications",
    category: "spesial",
    color: "text-slate-700",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
  },
  {
    id: "widget-my-tasks",
    label: "My tasks",
    description: "Your actions and due dates",
    icon: Clock,
    href: "/dashboard/actions",
    category: "spesial",
    color: "text-amber-700",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
  },
];

// Fallback-sett for helt ukjent bransje
export const DEFAULT_WIDGET_IDS = menuPathsToWidgetIds([...CORE_HSEQ_NAV_HREFS]);

/** Industry does not change dashboard tiles. Core HSEQ is the same for every employer. */
export function getDefaultWidgetIdsForIndustry(_industry?: string | null): string[] {
  return DEFAULT_WIDGET_IDS;
}

export function getWidgetById(id: string): WidgetDefinition | undefined {
  return WIDGET_REGISTRY.find((w) => w.id === id);
}
