import {
  AlertTriangle,
  FileText,
  ShieldAlert,
  ClipboardCheck,
  GraduationCap,
  CheckSquare,
  Beaker,
  Flame,
  Droplets,
  Zap,
  Building2,
  UtensilsCrossed,
  Stethoscope,
  SprayCan,
  CalendarDays,
  BookOpen,
  HardHat,
  FileWarning,
  Heart,
  Leaf,
  ShieldCheck,
  Search,
  Users,
  Target,
  MessageSquareWarning,
  MessageSquare,
  ScrollText,
  type LucideIcon,
  BarChart3,
  ListTodo,
  Sparkles,
  Activity,
  Clock,
  Siren,
  Gauge,
  Megaphone,
  Scale,
  Truck,
  TreePine,
  PersonStanding,
  MapPin,
  Moon,
  UserCheck,
  Radar,
  BookOpenCheck,
} from "lucide-react";
import { BRANSJE_MODULES } from "@/lib/bransje-modules";
import { menuPathsToWidgetIds } from "@/lib/menu-widget-sync";

export interface WidgetDefinition {
  id: string;
  label: string;
  description: string;
  icon: LucideIcon;
  href: string;
  category: WidgetCategory;
  color: string;
  bgColor: string;
  borderColor: string;
  permission?: string;
  isAdvanced?: boolean;
}

export type WidgetCategory =
  | "hms"
  | "sikkerhet"
  | "helse"
  | "dokumenter"
  | "personal"
  | "kvalitet"
  | "spesial";

export const WIDGET_CATEGORIES: Record<WidgetCategory, { label: string; color: string }> = {
  hms: { label: "HMS Kjerne", color: "text-blue-700" },
  sikkerhet: { label: "Sikkerhet & Beredskap", color: "text-red-700" },
  helse: { label: "Helse & Miljø", color: "text-emerald-700" },
  dokumenter: { label: "Dokumenter & Rutiner", color: "text-slate-700" },
  personal: { label: "Personal & Administrasjon", color: "text-amber-700" },
  kvalitet: { label: "Kvalitet & Forbedring", color: "text-indigo-700" },
  spesial: { label: "Dashboard-widgeter", color: "text-purple-700" },
};

export const WIDGET_REGISTRY: WidgetDefinition[] = [
  // HMS Kjerne
  {
    id: "incidents",
    label: "Avvik",
    description: "Hendelser, avvik og uønskede hendelser (AML § 5-2)",
    icon: AlertTriangle,
    href: "/dashboard/incidents",
    category: "hms",
    color: "text-orange-700",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    permission: "incidents",
  },
  {
    id: "risks",
    label: "Risiko­kartlegging",
    description: "Risikovurderinger og risikomatrise",
    icon: ShieldAlert,
    href: "/dashboard/risks",
    category: "hms",
    color: "text-red-700",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    permission: "risks",
    isAdvanced: true,
  },
  {
    id: "actions",
    label: "Tiltak",
    description: "Korrigerende og forebyggende tiltak",
    icon: CheckSquare,
    href: "/dashboard/actions",
    category: "hms",
    color: "text-blue-700",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    permission: "actions",
  },
  {
    id: "inspections",
    label: "Vernerunde",
    description: "Vernerunder og inspeksjoner",
    icon: ClipboardCheck,
    href: "/dashboard/inspections",
    category: "hms",
    color: "text-teal-700",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    permission: "inspections",
  },
  {
    id: "sja",
    label: "SJA",
    description: "Sikker Jobb Analyse",
    icon: HardHat,
    href: "/dashboard/sja",
    category: "hms",
    color: "text-yellow-700",
    bgColor: "bg-yellow-50",
    borderColor: "border-yellow-200",
    permission: "sja",
  },
  {
    id: "ruh",
    label: "RUH",
    description: "Rapport uønsket hendelse",
    icon: FileWarning,
    href: "/dashboard/ruh",
    category: "hms",
    color: "text-amber-700",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
    permission: "ruh",
  },
  {
    id: "training",
    label: "Opplæring",
    description: "Opplæring og kompetanse for ansatte",
    icon: GraduationCap,
    href: "/dashboard/training",
    category: "hms",
    color: "text-purple-700",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
    permission: "training",
  },

  // Sikkerhet & Beredskap
  {
    id: "fire-safety",
    label: "Brannøvelse",
    description: "Planlegg, gjennomfør og evaluer brannøvelser (§ 12 og § 13)",
    icon: Flame,
    href: "/dashboard/fire-drills",
    category: "sikkerhet",
    color: "text-red-600",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    permission: "inspections",
  },
  {
    id: "electrical",
    label: "Samsvarserklæringer",
    description: "Elektro, rørlegger, ventilasjon og andre fag",
    icon: Zap,
    href: "/dashboard/samsvarserklaringer",
    category: "sikkerhet",
    color: "text-yellow-600",
    bgColor: "bg-yellow-50",
    borderColor: "border-yellow-200",
  },
  {
    id: "water-safety",
    label: "Vann",
    description: "Vannsikkerhet og legionella-kontroll",
    icon: Droplets,
    href: "/dashboard/rutiner?q=vann",
    category: "sikkerhet",
    color: "text-cyan-600",
    bgColor: "bg-cyan-50",
    borderColor: "border-cyan-200",
  },
  {
    id: "elevator",
    label: "Heis",
    description: "Heiskontroll og vedlikehold",
    icon: Building2,
    href: "/dashboard/rutiner?q=heis",
    category: "sikkerhet",
    color: "text-slate-600",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
  },
  {
    id: "bcm",
    label: "Beredskap",
    description: "Beredskapsplaner og krisehåndtering (BCM)",
    icon: ShieldCheck,
    href: "/dashboard/bcm",
    category: "sikkerhet",
    color: "text-rose-700",
    bgColor: "bg-rose-50",
    borderColor: "border-rose-200",
    permission: "bcm",
    isAdvanced: true,
  },

  // Helse & Miljø
  {
    id: "chemicals",
    label: "Kjemikalier",
    description: "Stoffkartotek og kjemikaliehåndtering",
    icon: Beaker,
    href: "/dashboard/chemicals",
    category: "helse",
    color: "text-emerald-700",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    permission: "chemicals",
  },
  {
    id: "medicine",
    label: "Medisin",
    description: "Medisinhåndtering og oversikt",
    icon: Stethoscope,
    href: "/dashboard/rutiner?q=medisin",
    category: "helse",
    color: "text-pink-600",
    bgColor: "bg-pink-50",
    borderColor: "border-pink-200",
  },
  {
    id: "medical-equipment",
    label: "Medisinsk utstyr",
    description: "Oversikt over medisinsk utstyr og vedlikehold",
    icon: Siren,
    href: "/dashboard/rutiner?q=medisinsk%20utstyr",
    category: "helse",
    color: "text-rose-600",
    bgColor: "bg-rose-50",
    borderColor: "border-rose-200",
  },
  {
    id: "cleaning",
    label: "Renhold",
    description: "Renholdskontroll og hygiene",
    icon: SprayCan,
    href: "/dashboard/rutiner?q=renhold",
    category: "helse",
    color: "text-sky-600",
    bgColor: "bg-sky-50",
    borderColor: "border-sky-200",
  },
  {
    id: "food-safety",
    label: "Mat",
    description: "Matsikkerhet og hygienekontroll",
    icon: UtensilsCrossed,
    href: "/dashboard/rutiner?q=mat",
    category: "helse",
    color: "text-green-600",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
  },
  {
    id: "wellbeing",
    label: "Arbeidsmiljø",
    description: "Psykososialt arbeidsmiljø og trivsel",
    icon: Heart,
    href: "/dashboard/wellbeing",
    category: "helse",
    color: "text-pink-700",
    bgColor: "bg-pink-50",
    borderColor: "border-pink-200",
    permission: "wellbeing",
  },
  {
    id: "environment",
    label: "Miljø",
    description: "Miljøstyring og ytre miljø (ISO 14001)",
    icon: Leaf,
    href: "/dashboard/environment",
    category: "helse",
    color: "text-green-700",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    permission: "environment",
    isAdvanced: true,
  },

  // Dokumenter & Rutiner
  {
    id: "documents",
    label: "Dokumenter",
    description: "Dokumentstyring og versjonsadministrasjon",
    icon: FileText,
    href: "/dashboard/documents",
    category: "dokumenter",
    color: "text-slate-700",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
    permission: "documents",
  },
  {
    id: "routines",
    label: "Rutiner og instrukser",
    description: "Bedriftens rutiner, instrukser og prosedyrer",
    icon: BookOpen,
    href: "/dashboard/rutiner",
    category: "dokumenter",
    color: "text-indigo-600",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
  },

  // Personal & Administrasjon
  {
    id: "absence",
    label: "Ferie/Fravær",
    description: "Fravær, ferie og permisjoner",
    icon: CalendarDays,
    href: "/dashboard/time-registration",
    category: "personal",
    color: "text-amber-600",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
  },
  {
    id: "organization",
    label: "Organisasjon",
    description: "Organisasjonskart og hierarki (AML § 3-1)",
    icon: Users,
    href: "/dashboard/organisasjonskart",
    category: "personal",
    color: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
  },
  {
    id: "meetings",
    label: "Møter",
    description: "AMU-møter, verneombudsmøter og referat",
    icon: CalendarDays,
    href: "/dashboard/meetings",
    category: "personal",
    color: "text-indigo-600",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
    permission: "meetings",
    isAdvanced: true,
  },

  // Kvalitet & Forbedring
  {
    id: "audits",
    label: "Revisjoner",
    description: "Interne og eksterne revisjoner",
    icon: Search,
    href: "/dashboard/audits",
    category: "kvalitet",
    color: "text-indigo-700",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
    permission: "audits",
    isAdvanced: true,
  },
  {
    id: "goals",
    label: "Mål",
    description: "HMS-mål og KPI-oppfølging",
    icon: Target,
    href: "/dashboard/goals",
    category: "kvalitet",
    color: "text-emerald-700",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    permission: "goals",
    isAdvanced: true,
  },
  {
    id: "complaints",
    label: "Klager",
    description: "Kundeklager og reklamasjoner",
    icon: MessageSquareWarning,
    href: "/dashboard/complaints",
    category: "kvalitet",
    color: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    permission: "complaints",
    isAdvanced: true,
  },
  {
    id: "feedback",
    label: "Tilbake­meldinger",
    description: "Kundetilbakemeldinger og forbedringsforslag",
    icon: MessageSquare,
    href: "/dashboard/feedback",
    category: "kvalitet",
    color: "text-sky-600",
    bgColor: "bg-sky-50",
    borderColor: "border-sky-200",
    permission: "feedback",
    isAdvanced: true,
  },
  {
    id: "risk-register",
    label: "Risiko­register",
    description: "Samlet risikooversikt for virksomheten",
    icon: ScrollText,
    href: "/dashboard/risk-register",
    category: "kvalitet",
    color: "text-red-600",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    permission: "riskRegister",
    isAdvanced: true,
  },

  // Ledelse & Oversikt
  {
    id: "hms-cockpit",
    label: "HMS Cockpit",
    description: "Samlet HMS-score, trender og forbedringsforslag",
    icon: Gauge,
    href: "/dashboard/hms-cockpit",
    category: "kvalitet",
    color: "text-violet-700",
    bgColor: "bg-violet-50",
    borderColor: "border-violet-200",
    permission: "hmsCockpit",
  },
  {
    id: "hms-handbok",
    label: "HMS-håndbok",
    description: "Bedriftens levende HMS-håndbok (IK-HMS § 5)",
    icon: BookOpenCheck,
    href: "/dashboard/hms-handbok",
    category: "dokumenter",
    color: "text-blue-700",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    permission: "hmsHandbok",
  },
  {
    id: "annual-hms-plan",
    label: "Årsplan HMS",
    description: "Årsplan for HMS-arbeid (IK-HMS § 5 nr. 5)",
    icon: CalendarDays,
    href: "/dashboard/annual-hms-plan",
    category: "kvalitet",
    color: "text-teal-700",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    permission: "annualHmsPlan",
  },
  {
    id: "management-reviews",
    label: "Ledelsens gjennomgang",
    description: "Ledelsens gjennomgang av HMS-systemet (ISO 45001)",
    icon: Users,
    href: "/dashboard/management-reviews",
    category: "kvalitet",
    color: "text-slate-700",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
    permission: "managementReviews",
    isAdvanced: true,
  },
  {
    id: "legal-register",
    label: "Juridisk register",
    description: "Lover og forskrifter som gjelder bedriften",
    icon: Scale,
    href: "/dashboard/juridisk-register",
    category: "dokumenter",
    color: "text-amber-700",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
    permission: "legalRegister",
  },
  {
    id: "whistleblowing",
    label: "Varsling",
    description: "Varslingskanal for kritikkverdige forhold (AML § 2A)",
    icon: Megaphone,
    href: "/dashboard/whistleblowing",
    category: "kvalitet",
    color: "text-red-700",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    permission: "whistleblowing",
    isAdvanced: true,
  },
  {
    id: "employee-reviews",
    label: "Medarbeidersamtale",
    description: "Planlegging og gjennomføring av medarbeidersamtaler",
    icon: UserCheck,
    href: "/dashboard/medarbeidersamtale",
    category: "personal",
    color: "text-violet-600",
    bgColor: "bg-violet-50",
    borderColor: "border-violet-200",
    permission: "employeeReviews",
    isAdvanced: true,
  },

  // Bransje-spesifikke moduler
  {
    id: "exposure-register",
    label: "Eksponeringsregister",
    description: "Register over arbeidstakeres eksponering for helseskadelige stoffer",
    icon: Radar,
    href: "/dashboard/exposure-register",
    category: "helse",
    color: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    permission: "exposureRegister",
  },
  {
    id: "construction-compliance",
    label: "SHA / Byggherreforskriften",
    description: "Sikkerhet, helse og arbeidsmiljø på bygge-/anleggsplasser",
    icon: HardHat,
    href: "/dashboard/construction-compliance",
    category: "sikkerhet",
    color: "text-amber-700",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
    permission: "constructionCompliance",
  },
  {
    id: "ik-mat",
    label: "IK-Mat",
    description: "Internkontroll for mattrygghet (IK-Mat-forskriften)",
    icon: UtensilsCrossed,
    href: "/dashboard/ik-mat",
    category: "helse",
    color: "text-green-700",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    permission: "ikMat",
  },
  {
    id: "aktivitetssikkerhet",
    label: "Aktivitetssikkerhet",
    description: "Sikkerhet ved aktiviteter og opplevelser (Produktkontrolloven)",
    icon: PersonStanding,
    href: "/dashboard/aktivitetssikkerhet",
    category: "sikkerhet",
    color: "text-emerald-700",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    permission: "aktivitetssikkerhet",
  },
  {
    id: "transport",
    label: "Transport",
    description: "Transportløyver, sjåfør- og kjøretøykontroll",
    icon: Truck,
    href: "/dashboard/transport",
    category: "sikkerhet",
    color: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    permission: "transport",
  },
  {
    id: "bht-nattarbeid",
    label: "BHT / Nattarbeid",
    description: "Bedriftshelsetjeneste og nattarbeid (AML § 3-3, § 10-11)",
    icon: Moon,
    href: "/dashboard/bht-nattarbeid",
    category: "helse",
    color: "text-indigo-700",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
    permission: "bhtNattarbeid",
  },
  {
    id: "beredskap-reiseliv",
    label: "Beredskapsplan reiseliv",
    description: "Beredskapsplan for reiselivsbedrifter",
    icon: MapPin,
    href: "/dashboard/beredskap-reiseliv",
    category: "sikkerhet",
    color: "text-teal-600",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    permission: "inspections",
  },
  {
    id: "projects",
    label: "Prosjekter",
    description: "Prosjektstyring og prosjektbaserte avvik",
    icon: TreePine,
    href: "/dashboard/projects",
    category: "kvalitet",
    color: "text-cyan-700",
    bgColor: "bg-cyan-50",
    borderColor: "border-cyan-200",
    permission: "incidents",
  },

  // Spesial-widgeter (dashboard-spesifikke)
  {
    id: "widget-task-center",
    label: "Oppgavesenter",
    description: "Varsling for oppgaver som trenger oppfølging",
    icon: ListTodo,
    href: "/dashboard/actions",
    category: "spesial",
    color: "text-blue-700",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
  },
  {
    id: "widget-hms-score",
    label: "HMS-puls",
    description: "Overordnet HMS-status for tilsyn og revisjon",
    icon: BarChart3,
    href: "/dashboard/hms-pulse",
    category: "spesial",
    color: "text-emerald-700",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
  },
  {
    id: "widget-ai-assistant",
    label: "AI-assistent",
    description: "Varsler og anbefalinger",
    icon: Sparkles,
    href: "/dashboard/notifications",
    category: "spesial",
    color: "text-purple-700",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
  },
  {
    id: "widget-activity-feed",
    label: "Aktivitet",
    description: "Siste aktivitet som varsling",
    icon: Activity,
    href: "/dashboard/notifications",
    category: "spesial",
    color: "text-slate-700",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
  },
  {
    id: "widget-my-tasks",
    label: "Mine oppgaver",
    description: "Personlige oppgaver og frister",
    icon: Clock,
    href: "/dashboard/actions",
    category: "spesial",
    color: "text-amber-700",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
  },
];

// Fallback-sett for helt ukjent bransje
export const DEFAULT_WIDGET_IDS = [
  "hms-cockpit",
  "incidents",
  "actions",
  "inspections",
  "training",
  "routines",
  "documents",
  "hms-handbok",
  "widget-task-center",
  "widget-hms-score",
  "fire-safety",
  "electrical",
  "risks",
];

/**
 * Returnerer standard widget-IDer for en gitt bransje.
 * Bruker BRANSJE_MODULES som én kilde slik at enkel meny
 * og dashboard-fliser alltid er i synk.
 */
export function getDefaultWidgetIdsForIndustry(industry: string | null | undefined): string[] {
  const key = (industry || "").trim().toLowerCase();
  if (!key) return DEFAULT_WIDGET_IDS;

  const config = BRANSJE_MODULES[key];
  if (!config) return DEFAULT_WIDGET_IDS;

  return menuPathsToWidgetIds(config.modules);
}

export function getWidgetById(id: string): WidgetDefinition | undefined {
  return WIDGET_REGISTRY.find((w) => w.id === id);
}
