export const SAFETY_BOARD_SECTION_LABELS: Record<string, string> = {
  SHA_PLAN: "Construction phase plan",
  MANNSKAPSLISTE: "Daily site register",
  AVVIK_STATISTIKK: "Accident tally (no personal data)",
  RUH_LISTE: "Near miss / incident list",
  SJA_AKTIVE: "Live RAMS",
  VERNERUNDE_STATUS: "Workplace inspection status",
  KONTAKTINFO: "First aider, fire marshal, principal contractor",
  BEREDSKAPSPLAN: "Emergency plan",
  DOKUMENT_HUB: "Document hub",
  EKSTERN_LENKE: "External link",
  VAERMELDING: "Weather",
  KPI_DASHBOARD: "KPI dashboard",
  HMS_PLAN_AARSHJUL: "Annual H&S plan",
  FREMDRIFTSPLAN: "Programme",
  RIGGPLAN: "Site layout",
  RISIKOMATRISE: "Risk matrix",
  OPPLARING_STATUS: "Induction / competency",
  LOVKRAV_SJEKKLISTE: "CDM / legal checklist",
  NYHETER_MELDINGER: "Site notices",
  SNARVEIER: "Shortcuts",
  GJEST_SKJEMA: "Visitor / induction form",
  GJESTESERVICE_STATUS: "Visitor service status",
};
