"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { addRiskAssessmentItem, generateAiRiskAssessmentItem } from "@/server/actions/risk.actions";
import { useToast } from "@/hooks/use-toast";
import type { RiskCategory } from "@prisma/client";
import { Loader2, Sparkles } from "lucide-react";

const LEVEL_OPTIONS = [
  { value: "LOW", label: "Lav" },
  { value: "MEDIUM", label: "Moderat" },
  { value: "HIGH", label: "Høy" },
  { value: "CRITICAL", label: "Kritisk" },
] as const;

const WORKPLACE_CATEGORY_OPTIONS: Array<{ value: RiskCategory; label: string }> = [
  { value: "PSYCHOSOCIAL", label: "Psykososialt" },
  { value: "ERGONOMIC", label: "Ergonomisk" },
  { value: "ORGANISATIONAL", label: "Organisatorisk" },
  { value: "PHYSICAL", label: "Fysisk" },
  { value: "SAFETY", label: "Sikkerhet" },
  { value: "HEALTH", label: "Helse" },
  { value: "OPERATIONAL", label: "Operasjonell" },
  { value: "ENVIRONMENTAL", label: "Miljø" },
];

const AI_RISK_TYPE_OPTIONS = [
  "Arbeid i høyden",
  "Maskiner og utstyr",
  "Kjemikalier og eksponering",
  "Ergonomi og belastning",
  "Brann og eksplosjon",
  "Alenearbeid",
  "Trafikk og kjøretøy",
  "Støy og vibrasjoner",
  "Vold og trusler",
  "Psykososial belastning",
] as const;

interface RiskAssessmentItemFormProps {
  riskAssessmentId: string;
  tenantId: string;
  ownerId: string;
  onAdded?: () => void;
  autoGenerateAi?: boolean;
  initialAiRiskType?: string;
  initialIndustryContext?: string;
}

export function RiskAssessmentItemForm({
  riskAssessmentId,
  tenantId,
  ownerId,
  onAdded,
  autoGenerateAi = false,
  initialAiRiskType,
  initialIndustryContext,
}: RiskAssessmentItemFormProps) {
  const router = useRouter();
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [title, setTitle] = useState("");
  const [level, setLevel] = useState<"LOW" | "MEDIUM" | "HIGH" | "CRITICAL">("LOW");
  const [category, setCategory] = useState<RiskCategory>("PSYCHOSOCIAL");
  const [assessmentDate, setAssessmentDate] = useState(() =>
    new Date().toISOString().slice(0, 10)
  );
  const [nextReviewDate, setNextReviewDate] = useState(() => {
    const d = new Date();
    d.setFullYear(d.getFullYear() + 1);
    return d.toISOString().slice(0, 10);
  });
  const [beskrivelse, setBeskrivelse] = useState("");
  const [konsekvens, setKonsekvens] = useState("");
  const [aiRiskType, setAiRiskType] = useState<string>(() => {
    if (initialAiRiskType && AI_RISK_TYPE_OPTIONS.includes(initialAiRiskType as (typeof AI_RISK_TYPE_OPTIONS)[number])) {
      return initialAiRiskType;
    }
    return AI_RISK_TYPE_OPTIONS[0];
  });
  const [industryContext, setIndustryContext] = useState(initialIndustryContext ?? "");
  const [isGeneratingAi, setIsGeneratingAi] = useState(false);
  const [suggestedMeasures, setSuggestedMeasures] = useState<string[]>([]);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const handleGenerateAi = async () => {
    setIsGeneratingAi(true);
    try {
      const result = await generateAiRiskAssessmentItem({
        riskType: aiRiskType,
        category,
        industryContext: industryContext.trim() || undefined,
      });
      if (!result.success || !result.data) {
        toast({
          variant: "destructive",
          title: "Kunne ikke generere AI-forslag",
          description: result.error || "Ukjent feil",
        });
        return;
      }

      setTitle(result.data.title);
      setBeskrivelse(result.data.beskrivelse);
      setKonsekvens(result.data.konsekvens);
      setLevel(result.data.level as "LOW" | "MEDIUM" | "HIGH" | "CRITICAL");
      setCategory(result.data.category as RiskCategory);
      setSuggestedMeasures(result.data.suggestedMeasures ?? []);

      toast({
        title: "AI-forslag klart",
        description: "Feltene er fylt ut. Kontroller og trykk Legg til risikopunkt.",
      });
    } finally {
      setIsGeneratingAi(false);
    }
  };

  useEffect(() => {
    if (!autoGenerateAi || hasAutoGenerated || isGeneratingAi) {
      return;
    }
    setHasAutoGenerated(true);
    void handleGenerateAi();
  }, [autoGenerateAi, hasAutoGenerated, isGeneratingAi]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const trimmed = title.trim();
    if (trimmed.length < 3) {
      toast({ variant: "destructive", title: "Tittel må være minst 3 tegn" });
      return;
    }
    setLoading(true);
    try {
      const result = await addRiskAssessmentItem({
        riskAssessmentId,
        tenantId,
        ownerId,
        title: trimmed,
        level,
        category,
        assessmentDate: assessmentDate || null,
        nextReviewDate: nextReviewDate || null,
        beskrivelse: beskrivelse.trim() || null,
        konsekvens: konsekvens.trim() || null,
        suggestedMeasures,
      });
      if (result.success) {
        toast({ title: "Risikopunkt lagt til", className: "bg-green-50 border-green-200" });
        setTitle("");
        setBeskrivelse("");
        setKonsekvens("");
        setSuggestedMeasures([]);
        onAdded?.();
        router.refresh();
      } else {
        toast({ variant: "destructive", title: "Feil", description: result.error });
      }
    } catch {
      toast({ variant: "destructive", title: "Feil", description: "Kunne ikke legge til" });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Legg til risikopunkt</CardTitle>
        <CardDescription>
          Tittel, beskrivelse, konsekvens, nivå, kategori og dato (ISO 45001)
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="rounded-md border bg-muted/30 p-3 space-y-3">
            <div className="space-y-2">
              <Label>AI-forslag for din bransje</Label>
              <Select value={aiRiskType} onValueChange={setAiRiskType} disabled={loading || isGeneratingAi}>
                <SelectTrigger>
                  <SelectValue placeholder="Velg risikotype" />
                </SelectTrigger>
                <SelectContent>
                  {AI_RISK_TYPE_OPTIONS.map((option) => (
                    <SelectItem key={option} value={option}>
                      {option}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="ai-industry-context">Underbransje / arbeidstype (valgfritt)</Label>
              <Input
                id="ai-industry-context"
                value={industryContext}
                onChange={(e) => setIndustryContext(e.target.value)}
                placeholder="F.eks. distribusjon av matvarer, kranbil, terminaldrift"
                disabled={loading || isGeneratingAi}
              />
            </div>
            <Button
              type="button"
              variant="secondary"
              onClick={handleGenerateAi}
              disabled={loading || isGeneratingAi}
            >
              {isGeneratingAi ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Genererer forslag...
                </>
              ) : (
                <>
                  <Sparkles className="mr-2 h-4 w-4" />
                  AI-forslag for din bransje
                </>
              )}
            </Button>
          </div>

          <div className="grid gap-4 md:grid-cols-3">
            <div className="space-y-2">
              <Label htmlFor="item-title">Tittel / kort beskrivelse *</Label>
              <Input
                id="item-title"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="F.eks. Manglende medvirkning i beslutningsprosesser"
                minLength={3}
                disabled={loading}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="item-date">Vurderingsdato</Label>
              <Input
                id="item-date"
                type="date"
                value={assessmentDate}
                onChange={(e) => setAssessmentDate(e.target.value)}
                disabled={loading}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="item-next-review">Neste revisjon</Label>
              <Input
                id="item-next-review"
                type="date"
                value={nextReviewDate}
                onChange={(e) => setNextReviewDate(e.target.value)}
                disabled={loading}
              />
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="item-beskrivelse">Beskrivelse</Label>
            <Textarea
              id="item-beskrivelse"
              value={beskrivelse}
              onChange={(e) => setBeskrivelse(e.target.value)}
              placeholder="Beskriv situasjonen, hvor det kan skje, hvem som er utsatt, etc."
              disabled={loading}
              rows={3}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="item-konsekvens">Konsekvens</Label>
            <Textarea
              id="item-konsekvens"
              value={konsekvens}
              onChange={(e) => setKonsekvens(e.target.value)}
              placeholder="Hva kan skje dersom risikoscenarioet inntreffer? Beskriv konsekvensen."
              disabled={loading}
              rows={3}
            />
          </div>
          {suggestedMeasures.length > 0 && (
            <div className="space-y-2">
              <Label htmlFor="item-tiltak">Foreslåtte tiltak (opprettes automatisk)</Label>
              <Textarea
                id="item-tiltak"
                value={suggestedMeasures.map((item, index) => `${index + 1}. ${item}`).join("\n")}
                readOnly
                rows={4}
              />
            </div>
          )}
          <div className="grid gap-4 md:grid-cols-3">
            <div className="space-y-2">
              <Label>Nivå</Label>
              <Select
                value={level}
                onValueChange={(v) => setLevel(v as "LOW" | "MEDIUM" | "HIGH" | "CRITICAL")}
                disabled={loading}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {LEVEL_OPTIONS.map((opt) => (
                    <SelectItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Kategori</Label>
              <Select value={category} onValueChange={(v: RiskCategory) => setCategory(v)} disabled={loading}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {WORKPLACE_CATEGORY_OPTIONS.map((opt) => (
                    <SelectItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          <Button type="submit" disabled={loading}>
            {loading ? "Legger til..." : "Legg til risikopunkt"}
          </Button>
        </form>
      </CardContent>
    </Card>
  );
}
