-- AI Pro add-on fields on Tenant (£30/month)
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "aiAddonEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "aiAddonEnabledAt" TIMESTAMPTZ;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "aiMonthlyCallCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "aiMonthlyCallResetAt" TIMESTAMPTZ;
